### ISSUE TITLE
Question: Porting to Omeka-S

### ISSUE THREAD

**Issue by m-art-in** [utlib/IiifItems#16]
Thank you very much for this plugin. It's working great. Do you have plans to port this module for Omeka-S? There is a posibility to use [Omeka-S as IIIF-Image-Server](https://github.com/Daniel-KM/Omeka-S-module-IiifServer)  so with your IIIFItems there would be a whole in one solution.
I'm not an expert php programmer but have basic knowledge and would like to help.

**Comment by dicksonlaw583** [comment]
Sorry for the late reply. I have been waiting for a response from University of Toronto's copyright office, since the plugin was developed as part of a Mellon-funded project. The project has concluded last year and I don't know of any imminent plans by the university to deploy Omeka S, let alone porting the plugin to use it on. However, it does look promising as a personal project, so I will keep you updated as to how the licensing will work if it can proceed.

**Comment by m-art-in** [comment]
ok, would be great to see this plugin running for Omeka S.
