### ISSUE TITLE
Can not import this manifest including 3D model json file.

### ISSUE THREAD

**Issue by fishfree** [utlib/IiifItems#17]
The manifest URL is: http://files.universalviewer.io/manifests/nelis/ecorche.json It has a application/vnd.threejs+json MIME file: http://files.universalviewer.io/manifests/nelis/ecorche/ecorche.json
It shows completed status, but no items imported, as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/72519697-da798880-3892-11ea-9e24-6cc1688e3c92.png)

**Comment by dicksonlaw583** [comment]
This plugin does not support IXIF manifests.

**Comment by fishfree** [comment]
@dicksonlaw583 No wnoder. But would you please tell me why and how to make this?

**Comment by dicksonlaw583** [comment]
IXIF is not an official specification of IIIF, so that was out of scope during the plugin's development. In addition, this plugin is no longer in the active development phase, so no major changes or additions are planned.

If you will only be displaying 3D IXIF content, it would be easier to just embed a Universal Viewer instance using an iframe (i.e. `<iframe src="http://universalviewer.io/examples/uv/uv.html#?manifest=http://files.universalviewer.io/manifests/nelis/ecorche.json"></iframe>`).

If you will be displaying IXIF content frequently and Omeka S is an option for you, you may want to consider this: https://omeka.org/s/modules/IiifServer/ (please note that I am not affiliated with this Omeka S plugin)

**Comment by fishfree** [comment]
@dicksonlaw583 Got it, Thank you very much!
